Repository CS2103JAN2018-F14-B4/main, pull requests merged in 2018-04, with the labels that each got.

#123 Fix appveyor test issues
  appveyor.yml
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.accepted

#116 Display book description in WebView
  src/main/java/seedu/address/model/book/Description.java
  src/main/java/seedu/address/network/api/google/JsonBookDetails.java
  src/main/java/seedu/address/ui/BookDescriptionView.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BookDescriptionView.fxml
  src/main/resources/view/BookDetailsPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/WhiteTheme.css
  src/test/java/guitests/guihandles/BookDescriptionViewHandle.java
  src/test/java/guitests/guihandles/BookDetailsPanelHandle.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
Labels: status.accepted

#126 Bump TestFX version
  build.gradle
  src/main/java/seedu/address/ui/BookDescriptionView.java
Labels: status.accepted

#127 Disable the command box when a long-running action is active
  appveyor.yml
  src/main/java/seedu/address/commons/events/ui/DisableCommandBoxRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/EnableCommandBoxRequestEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/WhiteTheme.css
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/BookListPanelHandle.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/RecentBooksPanelHandle.java
  src/test/java/guitests/guihandles/SearchResultsPanelHandle.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/ReviewsCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status.accepted

#129 Add book image to book details panel
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/resources/view/BookDetailsPanel.fxml
Labels: status.completed

#130 Add icons to author and category tags
  src/main/java/seedu/address/model/book/Author.java
  src/main/java/seedu/address/model/book/Category.java
  src/main/java/seedu/address/ui/BookCard.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/test/java/guitests/guihandles/BookCardHandle.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.accepted

#131 Keep the ordering of authors and categories as per original API data
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/model/UniqueList.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/util/BookDataUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/network/api/google/JsonBookDetails.java
  src/main/java/seedu/address/network/api/google/JsonSearchResults.java
  src/main/java/seedu/address/storage/XmlAdaptedBook.java
  src/test/java/seedu/address/model/UniqueListTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/model/book/UniqueBookListTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
Labels: status.accepted

#133 Annotate code for collation and add output of collate
  collated/functional/takuyakanbr.md
  collated/test/takuyakanbr.md
  src/main/java/seedu/address/commons/core/Theme.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/network/HttpClient.java
  src/main/java/seedu/address/network/HttpResponse.java
  src/main/java/seedu/address/network/Network.java
  src/main/java/seedu/address/network/NetworkManager.java
  src/main/java/seedu/address/network/api/google/GoogleBooksApi.java
  src/main/java/seedu/address/network/api/google/JsonBookDetails.java
  src/main/java/seedu/address/network/api/google/JsonDeserializer.java
  src/main/java/seedu/address/network/api/google/JsonSearchResults.java
  src/main/resources/view/BookDetailsPanel.fxml
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/network/NetworkManagerTest.java
  src/test/java/seedu/address/network/api/google/GoogleBooksApiTest.java
  src/test/java/seedu/address/network/api/google/JsonDeserializerTest.java
  src/test/java/systemtests/ListCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/ThemeCommandSystemTest.java
Labels: status.accepted

#136 Add collate
  collated/functional/qiu-siqi.md
  collated/test/qiu-siqi.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RecentCommand.java
  src/main/java/seedu/address/logic/commands/ReviewsCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ReviewsCommandParser.java
  src/main/java/seedu/address/model/book/UniqueBookCircularList.java
  src/main/java/seedu/address/storage/XmlRecentBooksStorage.java
  src/main/java/seedu/address/ui/BookDescriptionView.java
  src/test/java/guitests/guihandles/BookDescriptionViewHandle.java
  src/test/java/guitests/guihandles/BookReviewsPanelHandle.java
  src/test/java/guitests/guihandles/RecentBooksPanelHandle.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RecentCommandTest.java
  src/test/java/seedu/address/logic/commands/ReviewsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ReviewsCommandParserTest.java
  src/test/java/seedu/address/model/book/UniqueBookCircularListTest.java
  src/test/java/seedu/address/storage/XmlRecentBooksStorageTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ReviewsCommandSystemTest.java
Labels: status.accepted

#137 Update README and user guide
  README.adoc
  docs/UserGuide.adoc
  docs/images/AddCommandAdded.png
  docs/images/AddCommandAddedConfirmation.png
  docs/images/AddCommandAdding.png
  docs/images/ClearCommand.png
  docs/images/DeleteCommand.png
  docs/images/ListCommand.png
  docs/images/RecentCommand.png
  docs/images/ReviewsCommandList.png
  docs/images/ReviewsCommandLoaded.png
  docs/images/ReviewsCommandLoading.png
  docs/images/ReviewsCommandScrollDown.png
  docs/images/SearchCommandFound.png
  docs/images/SearchCommandSearching.png
  docs/images/SelectCommand.png
  docs/images/SelectCommandUI.png
  docs/images/ThemeDark.png
  docs/images/ThemeLight.png
  docs/images/ThemeWhite.png
  docs/images/Ui.png
  docs/images/UndoCommand.png
Labels: status.completed

#139 Bump version to v1.4
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
Labels: status.completed

#132 Add welcome panel
  copyright.txt
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/WelcomePanel.java
  src/main/resources/images/book_flat_128.png
  src/main/resources/text/quotes.txt
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/WelcomePanel.fxml
  src/main/resources/view/WhiteTheme.css
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WelcomePanelHandle.java
  src/test/java/systemtests/BibliotekSystemTest.java
Labels: status.accepted, type.enhancement

#153 Add additional tests
  src/main/java/seedu/address/commons/exceptions/IllegalValueException.java
  src/main/java/seedu/address/commons/exceptions/InvalidThemeException.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/address/model/BookShelf.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/logic/commands/RecentCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/model/BookShelfTest.java
  src/test/java/seedu/address/model/book/GidTest.java
  src/test/java/seedu/address/model/book/PublicationDateTest.java
  src/test/java/seedu/address/model/book/PublisherTest.java
  src/test/java/seedu/address/network/NetworkManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedBookTest.java
  src/test/java/seedu/address/storage/XmlSerializableBookShelfTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/SearchResultsPanelTest.java
Labels: status.accepted

#155 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/NetworkComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/DeleteBookSdForLogic.png
  docs/images/ModelClassDiagram.png
  docs/images/NetworkClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/getting-started-ui-result-after.png
  docs/images/getting-started-ui-result-before.png
  docs/images/getting-started-ui-status-after.png
  docs/images/getting-started-ui-status-before.png
  docs/images/getting-started-ui-tag-after.png
  docs/images/getting-started-ui-tag-before.png
Labels: status.accepted

#156 Add getActiveList in model
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LibraryCommand.java
  src/main/java/seedu/address/logic/commands/ReviewsCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ReviewsCommandTest.java
Labels: status.accepted

#151 COLLATE
  collated/functional/592363789.md
  collated/test/592363789.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/book/Rating.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/book/RatingTest.java
Labels: status.accepted

#160 Improve UI consistency across OSes
  copyright.txt
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/OpenSansEmoji.ttf
  src/main/resources/view/WhiteTheme.css
Labels: status.accepted

#161 Fix saving of window position when UI is minimized
  src/main/java/seedu/address/ui/UiManager.java
Labels: status.accepted

#162 Restrict the number of help windows to 1
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: status.accepted

#163 Update search command
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/network/api/google/GoogleBooksApi.java
  src/main/java/seedu/address/network/api/google/JsonDeserializer.java
  src/main/java/seedu/address/network/api/google/JsonSearchResults.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchDescriptorTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/network/api/google/JsonDeserializerTest.java
  src/test/java/seedu/address/testutil/SearchDescriptorBuilder.java
  src/test/java/systemtests/SearchCommandSystemTest.java
Labels: status.accepted

#164 Fix use of WebViewManager
  src/main/java/seedu/address/ui/BookInLibraryPanel.java
  src/main/java/seedu/address/ui/BookReviewsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/ui/BookReviewsPanelTest.java
Labels: status.accepted

#165 Adjust UI styling and sizing
  src/main/resources/view/BookDescriptionView.fxml
  src/main/resources/view/BookDetailsPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/WhiteTheme.css
Labels: status.accepted

#167 Remove duplicated code in XmlRecentBooksStorage
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/storage/XmlRecentBooksStorage.java
Labels: status.accepted

#170 Make commands handle undo logic themselves
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/UndoCommand.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/test/java/seedu/address/logic/UndoStackTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: status.accepted

#171 Add command auto correction
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
Labels: status.accepted

#176 Collate code
  collated/functional/fishTT.md
Labels: status.accepted

#175 Add PPP
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/RecentCommandSequenceDiagram.pptx
  docs/images/SequenceDiagramRecentCommandEvent.png
  docs/images/SequenceDiagramRecentCommandLogic.png
  docs/team/qiu-siqi.adoc
Labels: status.accepted

#157 Update documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/correctkey.png
  docs/images/defaultbook.png
  docs/images/editseq.png
  docs/images/newbook.png
  docs/images/password_admin.png
  docs/images/setsuccess.png
  docs/images/shouldbedecryptfirst.png
  docs/images/wrongkey(set).png
  docs/images/wrongkey.png
  docs/team/shijin.adoc
Labels: status.completed

#179 Make commands case-insensitive
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/ReviewsCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status.accepted

#178 Add Events to fix command issues
  src/main/java/seedu/address/commons/events/ui/DeselectBookRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ReselectBookRequestEvent.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: status.accepted

#181 Bump version to v1.5rc
  src/main/java/seedu/address/MainApp.java
Labels: status.accepted

#183 Add delay to makeGetRequest on event of exception
  src/main/java/seedu/address/network/HttpClient.java
Labels: status.accepted

#184 Change behaviour for pressing Enter in CommandBox
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: status.accepted

#186 Add more tests for add and recent commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RecentCommandTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/RecentCommandSystemTest.java
Labels: status.accepted

#187 Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/LibraryCommandActivityDiagram.pptx
  docs/diagrams/RecentCommandListFive.pptx
  docs/diagrams/RecentCommandListFour.pptx
  docs/diagrams/RecentCommandListOne.pptx
  docs/diagrams/RecentCommandListThree.pptx
  docs/diagrams/RecentCommandListTwo.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/LibraryCommandActivityDiagram.png
  docs/images/RecentCommandListFive.png
  docs/images/RecentCommandListFour.png
  docs/images/RecentCommandListOne.png
  docs/images/RecentCommandListThree.png
  docs/images/RecentCommandListTwo.png
  docs/images/UiClassDiagram.png
Labels: status.accepted

#188 Update User Guide
  docs/UserGuide.adoc
  docs/images/CommandBox.png
  docs/images/LeftPanel.png
  docs/images/ResultBox.png
  docs/images/RightPanel.png
Labels: status.accepted

#190 Improve various parts of the code and tests
  docs/TestDocument.adoc
  src/main/java/seedu/address/commons/core/Theme.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/UndoStack.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/alias/Alias.java
  src/main/java/seedu/address/model/book/Priority.java
  src/main/java/seedu/address/model/book/Rating.java
  src/main/java/seedu/address/model/book/Status.java
  src/main/java/seedu/address/network/HttpClient.java
  src/main/java/seedu/address/network/api/google/JsonBookDetails.java
  src/main/java/seedu/address/network/api/google/JsonSearchResults.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedAlias.java
  src/main/java/seedu/address/storage/XmlAliasListStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlRecentBooksStorage.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/test/java/seedu/address/commons/core/ThemeTest.java
  src/test/java/seedu/address/logic/commands/ThemeCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/alias/UniqueAliasListTest.java
  src/test/java/seedu/address/network/HttpClientTest.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/ListCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
Labels: status.accepted

#192 Add test for case-insensitive commands
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
Labels: status.accepted

#194 Add tests for hint system
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/HintParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/HintParserTest.java
Labels: status.accepted

#195 Update collated code
  collated/functional/takuyakanbr.md
  collated/test/takuyakanbr.md
Labels: status.accepted

#198 Fix consistency issue with filtering and sorting
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: status.accepted

#134 Add encryption/decryption of book shelf data
  collated/functional/592363789-reused.md
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/PasswordChangedEvent.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/CipherEngine.java
  src/main/java/seedu/address/logic/LockManager.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LockCommand.java
  src/main/java/seedu/address/logic/commands/SetPasswordCommand.java
  src/main/java/seedu/address/logic/commands/UnlockCommand.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/HintParser.java
  src/main/java/seedu/address/logic/parser/SetPasswordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/XmlBookShelfStorage.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/LockCommandTest.java
  src/test/java/seedu/address/logic/commands/SetPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlockCommandTest.java
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SetPasswordCommandParserTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
Labels: status.accepted

#199 Refactor some stuff
  src/main/java/seedu/address/commons/util/CommandUtil.java
  src/main/java/seedu/address/logic/CommandAutocorrection.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LibraryCommand.java
  src/main/java/seedu/address/logic/commands/RecentCommand.java
  src/main/java/seedu/address/logic/commands/ReviewsCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/book/UniqueBookCircularList.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/CommandAutocorrectionTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
Labels: status.accepted

#200 Improve security of encryption system
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/AppUnlockedEvent.java
  src/main/java/seedu/address/commons/events/model/PasswordChangedEvent.java
  src/main/java/seedu/address/logic/CipherEngine.java
  src/main/java/seedu/address/logic/LockManager.java
  src/main/java/seedu/address/logic/commands/LockCommand.java
  src/main/java/seedu/address/logic/commands/SetPasswordCommand.java
  src/main/java/seedu/address/logic/commands/UnlockCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlBookShelfStorage.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/SetPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlockCommandTest.java
Labels: status.accepted

#204 Make minor changes to Developer Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: status.accepted

#201 Add some tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/CipherEngine.java
  src/main/java/seedu/address/logic/LockManager.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/CipherEngineTest.java
  src/test/java/seedu/address/logic/LockManagerTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LockCommandTest.java
  src/test/java/seedu/address/logic/commands/SetPasswordCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlockCommandTest.java
  src/test/java/seedu/address/storage/XmlAliasListStorageTest.java
  src/test/java/seedu/address/storage/XmlBookShelfStorageTest.java
  src/test/java/seedu/address/storage/XmlRecentBooksStorageTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/systemtests/BibliotekSystemTest.java
Labels: status.accepted

#203 Update User Guide
  docs/UserGuide.adoc
  docs/images/AddCommandAdded.png
  docs/images/AddCommandAddedConfirmation.png
  docs/images/AddCommandAdding.png
  docs/images/AliasesCommand.png
  docs/images/ClearCommand.png
  docs/images/CommandAutocorrection.png
  docs/images/DeleteCommand.png
  docs/images/EditCommandMid.png
  docs/images/EditCommandStart.png
  docs/images/HintSystem.png
  docs/images/HintSystemNextParameter.png
  docs/images/LeftPanel.png
  docs/images/LibraryCommandAfter.png
  docs/images/LibraryCommandBefore.png
  docs/images/LibraryCommandSearching.png
  docs/images/ListCommand.png
  docs/images/LockCommand.png
  docs/images/LockCommandMessage.png
  docs/images/RecentCommand.png
  docs/images/ReviewsCommandLoaded.png
  docs/images/RightPanel.png
  docs/images/SearchCommandFound.png
  docs/images/SearchCommandSearching.png
  docs/images/SelectCommand.png
  docs/images/SelectCommandUI.png
  docs/images/ThemeDark.png
  docs/images/ThemeLight.png
  docs/images/ThemeWhite.png
  docs/images/Ui.png
  docs/images/UndoCommand.png
  docs/images/UnlockCommand.png
Labels: status.accepted

#207 Add command alias system to developer guide
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/AliasApplication.pptx
  docs/diagrams/AliasSampleCommand.pptx
  docs/diagrams/AliasSampleCommand2.pptx
  docs/diagrams/SearchCommandSequenceDiagram.pptx
  docs/images/AliasApplication.png
  docs/images/AliasSampleCommand.png
  docs/images/AliasSampleCommand2.png
  docs/images/SearchCommandSequenceDiagram.png
  docs/team/johndoe.adoc
  docs/team/takuyakanbr.adoc
  src/main/java/seedu/address/commons/events/model/AliasListChangedEvent.java
  src/main/java/seedu/address/logic/parser/AddAliasCommandParser.java
Labels: status.accepted

#206 Add some tests and collate for test
  collated/functional/592363789.md
  collated/test/592363789.md
  collated/unused/592363789-unused.md
  src/main/java/seedu/address/commons/events/model/PasswordChangedEvent.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/LockCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlockCommandTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: status.accepted

#208 Finalize collate
  collated/functional/qiu-siqi.md
  collated/test/qiu-siqi.md
  src/test/java/guitests/guihandles/BookInLibraryPanelHandle.java
  src/test/java/systemtests/LibraryCommandSystemTest.java
Labels: status.accepted

#205 Finalize PPP
  docs/DeveloperGuide.adoc
  docs/images/LibraryCommandAfter.png
  docs/images/LibraryCommandBefore.png
  docs/images/LibraryCommandSearching.png
  docs/team/qiu-siqi.adoc
Labels: status.accepted

#210 Add more tests for lock system
  src/test/java/seedu/address/logic/LockManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/systemtests/LockCommandSystemTest.java
Labels: status.accepted

#209 Fix various issues
  docs/team/takuyakanbr.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/CipherEngine.java
  src/main/java/seedu/address/logic/commands/SetPasswordCommand.java
  src/main/java/seedu/address/logic/commands/UnlockCommand.java
  src/main/java/seedu/address/logic/parser/HintParser.java
  src/test/java/seedu/address/logic/CipherEngineTest.java
  src/test/java/seedu/address/logic/parser/HintParserTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
Labels: status.accepted

#211 Refactor a method and make style changes
  collated/test/qiu-siqi.md
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ReviewsCommandTest.java
  src/test/java/seedu/address/network/NetworkManagerTest.java
  src/test/java/seedu/address/network/library/NlbResultHelperTest.java
  src/test/java/seedu/address/storage/XmlRecentBooksStorageTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: status.accepted

#214 Update sample book shelf
  src/main/java/seedu/address/commons/util/XmlUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/data/sampleBookShelf.xml
  src/test/java/systemtests/SampleDataTest.java
Labels: status.accepted

#215 Add testing instructions
  docs/DeveloperGuide.adoc
Labels: status.accepted

#213 Bump version to v1.5
  src/main/java/seedu/address/MainApp.java
Labels: status.accepted
