Repository CS2103JAN2018-F14-B4/main, pull requests merged in 2018-03, with the labels that each got.

#9 Rebrand app
  README.adoc
  copyright.txt
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/book_flat_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: status: completed

#48 Add user case345
  docs/DeveloperGuide.adoc
Labels: status: completed

#49 Add storage for Book and BookShelf
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/BookShelfStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedAuthor.java
  src/main/java/seedu/address/storage/XmlAdaptedBook.java
  src/main/java/seedu/address/storage/XmlAdaptedCategory.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAdaptedTag.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlBookShelfStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/storage/XmlSerializableBookShelf.java
  src/test/data/XmlBookShelfStorageTest/NotXmlFormatBookShelf.xml
  src/test/data/XmlBookShelfStorageTest/invalidAndValidBookBookShelf.xml
  src/test/data/XmlBookShelfStorageTest/invalidBookBookShelf.xml
  src/test/data/XmlSerializableBookShelfTest/invalidBookBookShelf.xml
  src/test/data/XmlSerializableBookShelfTest/typicalBooksBookShelf.xml
  src/test/java/seedu/address/storage/StorageManagerAbTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedBookTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/storage/XmlBookShelfStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/XmlSerializableBookShelfTest.java
Labels: status: completed

#55 Change asciidoc styling
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/stylesheets/asciidoctor.css
  docs/stylesheets/gh-pages.css
Labels: status: completed

#58 Add Network component
  build.gradle
  src/main/java/seedu/address/commons/events/network/ApiBookDetailsRequestEvent.java
  src/main/java/seedu/address/commons/events/network/ApiBookDetailsResultEvent.java
  src/main/java/seedu/address/commons/events/network/ApiSearchRequestEvent.java
  src/main/java/seedu/address/commons/events/network/ApiSearchResultEvent.java
  src/main/java/seedu/address/commons/events/network/ResultOutcome.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/util/BookDataUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/network/HttpClient.java
  src/main/java/seedu/address/network/HttpResponse.java
  src/main/java/seedu/address/network/Network.java
  src/main/java/seedu/address/network/NetworkManager.java
  src/main/java/seedu/address/network/api/google/BookDeserializer.java
  src/main/java/seedu/address/network/api/google/BookShelfDeserializer.java
  src/main/java/seedu/address/network/api/google/GoogleBooksApi.java
  src/main/java/seedu/address/network/api/google/JsonDeserializer.java
  src/test/data/BookDeserializerTest/ErrorResponse.json
  src/test/data/BookDeserializerTest/InvalidResponseWrongType.json
  src/test/data/BookDeserializerTest/ValidResponse.json
  src/test/data/BookDeserializerTest/ValidResponseNoDesc.json
  src/test/data/BookShelfDeserializerTest/ErrorResponse.json
  src/test/data/BookShelfDeserializerTest/InvalidResponseWrongType.json
  src/test/data/BookShelfDeserializerTest/ValidResponse.json
  src/test/data/BookShelfDeserializerTest/ValidResponseNoDesc.json
  src/test/java/seedu/address/network/api/google/BookDeserializerTest.java
  src/test/java/seedu/address/network/api/google/BookShelfDeserializerTest.java
  src/test/java/seedu/address/network/api/google/GoogleBooksApiTest.java
  src/test/java/seedu/address/network/api/google/JsonDeserializerTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
Labels: status: completed

#60 Add additional tests for the model component
  src/test/java/seedu/address/model/BookShelfTest.java
  src/test/java/seedu/address/model/UniqueListTest.java
  src/test/java/seedu/address/model/book/AuthorTest.java
  src/test/java/seedu/address/model/book/CategoryTest.java
  src/test/java/seedu/address/model/book/DescriptionTest.java
  src/test/java/seedu/address/model/book/TitleTest.java
  src/test/java/seedu/address/model/book/UniqueBookListTest.java
Labels: status: accepted

#69 Add additional tests for network component
  src/main/java/seedu/address/network/NetworkManager.java
  src/test/data/BookShelfDeserializerTest/ValidResponseDuplicateBooks.json
  src/test/java/seedu/address/network/HttpClientTest.java
  src/test/java/seedu/address/network/NetworkManagerTest.java
  src/test/java/seedu/address/network/api/google/BookShelfDeserializerTest.java
  src/test/java/seedu/address/network/api/google/GoogleBooksApiTest.java
  src/test/java/seedu/address/ui/testutil/EventsCollectorRule.java
Labels: status: accepted

#70 Update readme
  README.adoc
  docs/LearningOutcomes.adoc
  docs/images/Ui.png
Labels: status: accepted

#72 Change add command and add more components to Book
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/Gid.java
  src/main/java/seedu/address/model/book/Isbn.java
  src/main/java/seedu/address/model/book/PublicationDate.java
  src/main/java/seedu/address/model/book/Publisher.java
  src/main/java/seedu/address/model/book/exceptions/InvalidBookException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/network/api/google/BookDeserializer.java
  src/main/java/seedu/address/network/api/google/BookShelfDeserializer.java
  src/main/java/seedu/address/storage/XmlAdaptedBook.java
  src/test/data/BookDeserializerTest/InvalidResponseNoIsbn.json
  src/test/data/BookShelfDeserializerTest/InvalidResponseNoIsbn.json
  src/test/data/XmlBookShelfStorageTest/invalidAndValidBookBookShelf.xml
  src/test/data/XmlSerializableBookShelfTest/typicalBooksBookShelf.xml
  src/test/data/XmlUtilTest/validBook.xml
  src/test/data/XmlUtilTest/validBookShelf.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/network/api/google/BookDeserializerTest.java
  src/test/java/seedu/address/network/api/google/BookShelfDeserializerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedBookTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/BookUtil.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
  src/test/java/seedu/address/ui/BookCardTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: status: completed

#73 Add book details panel
  src/main/java/seedu/address/commons/events/ui/BookListSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/SearchResultsSelectionChangedEvent.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SearchResultsPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/BookDetailsPanel.fxml
  src/main/resources/view/BookListCard.fxml
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/BookDetailsPanelHandle.java
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/address/ui/BookCardTest.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
  src/test/java/seedu/address/ui/BookListPanelTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: status: accepted

#74 Add a light-blue based theme
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/ui/testutil/UiPartRule.java
Labels: status: accepted

#68 Update User Guide
  docs/UserGuide.adoc
Labels: status: completed

#76 Fix AboutUs
  docs/AboutUs.adoc
  docs/images/fishTT.png
  docs/images/fishtt.png
Labels: status: accepted

#81 Update DeveloperGuide to add feature contribution
  docs/DeveloperGuide.adoc
Labels: status: completed

#79 Make book details panel scroll to top when selected book changes
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BookDetailsPanel.fxml
Labels: status: completed

#66 Add rating field to Book
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/Rating.java
  src/main/java/seedu/address/network/api/google/BookDeserializer.java
  src/main/java/seedu/address/network/api/google/BookShelfDeserializer.java
  src/main/java/seedu/address/storage/XmlAdaptedBook.java
  src/test/data/XmlBookShelfStorageTest/invalidAndValidBookBookShelf.xml
  src/test/data/XmlSerializableBookShelfTest/typicalBooksBookShelf.xml
  src/test/data/XmlUtilTest/missingBookField.xml
  src/test/data/XmlUtilTest/tempBookShelf.xml
  src/test/data/XmlUtilTest/validBook.xml
  src/test/data/XmlUtilTest/validBookShelf.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/book/RatingTest.java
  src/test/java/seedu/address/storage/XmlAdaptedBookTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
Labels: status: completed

#84 Updated DG
  docs/DeveloperGuide.adoc
Labels: status: accepted

#88 Refactor network component
  build.gradle
  src/main/java/seedu/address/network/HttpClient.java
  src/main/java/seedu/address/network/HttpResponse.java
  src/main/java/seedu/address/network/NetworkManager.java
  src/main/java/seedu/address/network/api/google/GoogleBooksApi.java
  src/main/java/seedu/address/network/api/google/JsonBookDetails.java
  src/main/java/seedu/address/network/api/google/JsonDeserializer.java
  src/main/java/seedu/address/network/api/google/JsonSearchResults.java
  src/test/data/JsonDeserializerTest/bookDetails/ErrorResponse.json
  src/test/data/JsonDeserializerTest/bookDetails/InvalidResponseNoIsbn.json
  src/test/data/JsonDeserializerTest/bookDetails/InvalidResponseWrongType.json
  src/test/data/JsonDeserializerTest/bookDetails/ValidResponse.json
  src/test/data/JsonDeserializerTest/bookDetails/ValidResponseNoDesc.json
  src/test/data/JsonDeserializerTest/search/ErrorResponse.json
  src/test/data/JsonDeserializerTest/search/InvalidResponseNoIsbn.json
  src/test/data/JsonDeserializerTest/search/InvalidResponseWrongType.json
  src/test/data/JsonDeserializerTest/search/ValidResponse.json
  src/test/data/JsonDeserializerTest/search/ValidResponseDuplicateBooks.json
  src/test/data/JsonDeserializerTest/search/ValidResponseNoDesc.json
  src/test/java/seedu/address/network/HttpClientTest.java
  src/test/java/seedu/address/network/NetworkManagerTest.java
  src/test/java/seedu/address/network/api/google/BookDeserializerTest.java
  src/test/java/seedu/address/network/api/google/BookShelfDeserializerTest.java
  src/test/java/seedu/address/network/api/google/GoogleBooksApiTest.java
  src/test/java/seedu/address/network/api/google/JsonDeserializerTest.java
Labels: status: completed

#86 Add recent command
  .gitignore
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/commons/events/ui/JumpToRecentBooksIndexRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/RecentBooksSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/SwitchToRecentBooksRequestEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RecentCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/main/java/seedu/address/model/ActiveListType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/book/UniqueBookCircularList.java
  src/main/java/seedu/address/storage/RecentBooksStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedBook.java
  src/main/java/seedu/address/storage/XmlRecentBooksStorage.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecentBooksPanel.java
  src/main/resources/view/RecentBooksPanel.fxml
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/RecentBooksPanelHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/RecentCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/book/UniqueBookCircularListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlRecentBooksStorageTest.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status: accepted

#85 Improve system tests
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/ThemeCommandSystemTest.java
Labels: status: accepted

#92 Add recent command to implementation in DG
  docs/DeveloperGuide.adoc
  docs/diagrams/RecentCommandListFive.pptx
  docs/diagrams/RecentCommandListFour.pptx
  docs/diagrams/RecentCommandListOne.pptx
  docs/diagrams/RecentCommandListThree.pptx
  docs/diagrams/RecentCommandListTwo.pptx
  docs/diagrams/RecentCommandSequenceDiagram.pptx
  docs/images/RecentCommandListFive.png
  docs/images/RecentCommandListFour.png
  docs/images/RecentCommandListOne.png
  docs/images/RecentCommandListThree.png
  docs/images/RecentCommandListTwo.png
  docs/images/SequenceDiagramRecentCommandEvent.png
  docs/images/SequenceDiagramRecentCommandLogic.png
Labels: status: accepted

#93 Update DG to describe implementation of search feature
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/NetworkComponentClassDiagram.pptx
  docs/diagrams/SearchCommandResultSequenceDiagram.pptx
  docs/diagrams/SearchCommandSequenceDiagram.pptx
  docs/diagrams/SearchRequestActivityDiagram.pptx
  docs/diagrams/SearchRequestSequenceDiagram.pptx
  docs/images/Architecture.png
  docs/images/NetworkClassDiagram.png
  docs/images/SearchCommandResultSequenceDiagram.png
  docs/images/SearchCommandSequenceDiagram.png
  docs/images/SearchRequestActivityDiagram.png
  docs/images/SearchRequestSequenceDiagram.png
Labels: status: accepted

#94 Bump version to v1.2
  src/main/java/seedu/address/MainApp.java
Labels: status: accepted

#95 Update build scripts
  .circleci/config.yml
  .travis.yml
  build.gradle
  docs/DummySearchPage.html
  gradle/wrapper/gradle-wrapper.properties
Labels: status.accepted

#96 Run junit tests in parallel
  build.gradle
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: status.accepted

#97 Add Priority and Status fields to Book
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/Priority.java
  src/main/java/seedu/address/model/book/Rating.java
  src/main/java/seedu/address/model/book/Status.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedBook.java
  src/main/java/seedu/address/ui/BookCard.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/resources/view/BookDetailsPanel.fxml
  src/main/resources/view/BookListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/WhiteTheme.css
  src/test/data/XmlSerializableBookShelfTest/typicalBooksBookShelf.xml
  src/test/data/XmlUtilTest/missingBookField.xml
  src/test/data/XmlUtilTest/validBook.xml
  src/test/data/XmlUtilTest/validBookShelf.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/model/book/RatingTest.java
  src/test/java/seedu/address/storage/XmlAdaptedBookTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
Labels: status.accepted

#105 Update badges and library list in README
  README.adoc
Labels: status.accepted

#104 Fix selection issues due to recent
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/RecentBooksPanel.java
  src/main/java/seedu/address/ui/SearchResultsPanel.java
Labels: status.completed

#107 Make ClearCommand clear BookDetailsPanel
  src/main/java/seedu/address/commons/events/ui/ClearBookDetailsRequestEvent.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/guitests/guihandles/BookDetailsPanelHandle.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
Labels: status.accepted

#108 Make BookCard when in view
  README.adoc
  build.gradle
  src/main/java/seedu/address/commons/events/ui/BookListSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/RecentBooksSelectionChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/SearchResultsSelectionChangedEvent.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/RecentBooksPanel.java
  src/main/java/seedu/address/ui/SearchResultsPanel.java
  src/test/java/guitests/guihandles/BookCardHandle.java
  src/test/java/guitests/guihandles/BookListPanelHandle.java
  src/test/java/guitests/guihandles/RecentBooksPanelHandle.java
  src/test/java/guitests/guihandles/SearchResultsPanelHandle.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.accepted

#112 Add command to view book reviews
  docs/UserGuide.adoc
  docs/images/ReviewsCommandList.png
  docs/images/ReviewsCommandLoaded.png
  docs/images/ReviewsCommandLoading.png
  docs/images/ReviewsCommandScrollDown.png
  src/main/java/seedu/address/commons/events/ui/ClearMainContentRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/ShowBookReviewsRequestEvent.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ReviewsCommand.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/main/java/seedu/address/logic/parser/ReviewsCommandParser.java
  src/main/java/seedu/address/ui/BookDetailsPanel.java
  src/main/java/seedu/address/ui/BookReviewsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/BookReviewsPanel.fxml
  src/test/java/guitests/guihandles/BookReviewsPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/logic/commands/ReviewsCommandTest.java
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
  src/test/java/seedu/address/logic/parser/ReviewsCommandParserTest.java
  src/test/java/seedu/address/ui/BookReviewsPanelTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/ReviewsCommandSystemTest.java
Labels: status.accepted

#114 Reduce time taken to compare UI book lists against book array
  src/test/java/guitests/guihandles/BookListPanelHandle.java
  src/test/java/guitests/guihandles/RecentBooksPanelHandle.java
  src/test/java/guitests/guihandles/SearchResultsPanelHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/ui/BookListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
Labels: status.accepted

#115 Make some changes in tests
  src/main/java/seedu/address/commons/events/model/BookShelfChangedEvent.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/model/BookShelfTest.java
  src/test/java/seedu/address/network/api/google/JsonDeserializerTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/BibliotekSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: status.accepted

#119 Bump version to v1.3
  src/main/java/seedu/address/MainApp.java
Labels: status.accepted

#121 Use randomized file name for recent books file when testing
  src/test/java/seedu/address/TestApp.java
Labels: status.completed

#111 Add edit command
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/BookShelfParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditDescriptorTest.java
  src/test/java/seedu/address/logic/parser/BookShelfParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/EditDescriptorBuilder.java
  src/test/java/seedu/address/ui/BookDetailsPanelTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ListCommandSystemTest.java
Labels: status.completed
